//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class restaurantdata
    {
        public string Name { get; set; }
        public string STLocation { get; set; }
        public string About { get; set; }
        public string MapLocation { get; set; }
        public string WorkTime { get; set; }
        public string Email_telephone { get; set; }
    }
}
